// Code generated by protoc-gen-go.
// source: res.proto
// DO NOT EDIT!

/*
Package res is a generated protocol buffer package.

It is generated from these files:
	res.proto

It has these top-level messages:
	Packet
*/
package res

import proto "code.google.com/p/goprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type Type int32

const (
	Type_SelectMan Type = 0
	Type_MoveMan   Type = 1
)

var Type_name = map[int32]string{
	0: "SelectMan",
	1: "MoveMan",
}
var Type_value = map[string]int32{
	"SelectMan": 0,
	"MoveMan":   1,
}

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}
func (x Type) String() string {
	return proto.EnumName(Type_name, int32(x))
}
func (x *Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Type_value, data, "Type")
	if err != nil {
		return err
	}
	*x = Type(value)
	return nil
}

type Man int32

const (
	Man_Whip    Man = 0
	Man_Density Man = 1
	Man_Vacuum  Man = 2
	Man_Normal  Man = 3
	Man_count   Man = 4
)

var Man_name = map[int32]string{
	0: "Whip",
	1: "Density",
	2: "Vacuum",
	3: "Normal",
	4: "count",
}
var Man_value = map[string]int32{
	"Whip":    0,
	"Density": 1,
	"Vacuum":  2,
	"Normal":  3,
	"count":   4,
}

func (x Man) Enum() *Man {
	p := new(Man)
	*p = x
	return p
}
func (x Man) String() string {
	return proto.EnumName(Man_name, int32(x))
}
func (x *Man) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Man_value, data, "Man")
	if err != nil {
		return err
	}
	*x = Man(value)
	return nil
}

type Packet struct {
	Type             *Type  `protobuf:"varint,1,req,name=type,enum=Type" json:"type,omitempty"`
	Man              *Man   `protobuf:"varint,2,opt,name=man,enum=Man" json:"man,omitempty"`
	X                *int64 `protobuf:"zigzag64,3,opt,name=x" json:"x,omitempty"`
	Y                *int64 `protobuf:"zigzag64,4,opt,name=y" json:"y,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Packet) Reset()         { *m = Packet{} }
func (m *Packet) String() string { return proto.CompactTextString(m) }
func (*Packet) ProtoMessage()    {}

func (m *Packet) GetType() Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Type_SelectMan
}

func (m *Packet) GetMan() Man {
	if m != nil && m.Man != nil {
		return *m.Man
	}
	return Man_Whip
}

func (m *Packet) GetX() int64 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *Packet) GetY() int64 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

func init() {
	proto.RegisterEnum("Type", Type_name, Type_value)
	proto.RegisterEnum("Man", Man_name, Man_value)
}
